StartupEvents.registry('item', event => {
    event.create('kubejs:hook_head')
    .texture('kubejs:item/hook_head')
    .displayName("钩爪头")
    .maxStackSize(1)
    event.create('kubejs:crushed_raw_desh')
    .texture('kubejs:item/crushed_raw_desh')
    event.create('kubejs:crushed_raw_calorite')
    .texture('kubejs:item/crushed_raw_calorite')
    event.create('kubejs:crushed_raw_ostrum')
    .texture('kubejs:item/crushed_raw_ostrum')
})
