StartupEvents.registry('item', event => {
	event.create('kubejs:advanced_cabin')
    .texture('kubejs:item/advanced_cabin')
	event.create('kubejs:advanced_plating')
    .texture('kubejs:item/advanced_plating')
	event.create('kubejs:basic_cabin')
    .texture('kubejs:item/basic_cabin')
	event.create('kubejs:basic_crystal_pannel')
    .texture('kubejs:item/basic_crystal_pannel')
	event.create('kubejs:basic_plating')
    .texture('kubejs:item/basic_plating')
	event.create('kubejs:basic_propeller')
    .texture('kubejs:item/basic_propeller')
	event.create('kubejs:columbus_propeller')
    .texture('kubejs:item/columbus_propeller')
	event.create('kubejs:explorer_cabin')
    .texture('kubejs:item/explorer_cabin')
	event.create('kubejs:flare_plating')
    .texture('kubejs:item/flare_plating')
	event.create('kubejs:hologram_frontpanel')
    .texture('kubejs:item/hologram_frontpanel')
	event.create('kubejs:moon_crystal_panel')
    .texture('kubejs:item/moon_crystal_panel')
	event.create('kubejs:moon_propeller')
    .texture('kubejs:item/moon_propeller')
	event.create('kubejs:venus_plating')
    .texture('kubejs:item/venus_plating')

    event.create('kubejs:healing_paste', 'heal_item')
    .texture('kubejs:item/healing_paste')
    .useDuration(itemstack => 30)
    .useAnimation("bow")
    .finishUsing((itemstack, level, entity) => {
        let effects = entity.potionEffects
        effects.add('minecraft:regeneration', 6, 1, false, false)
    })
    event.create('kubejs:weak_bandage', 'heal_item')
    .texture('kubejs:item/weak_bandage')
    .useDuration(itemstack => 30)
    .useAnimation("bow")
    .finishUsing((itemstack, level, entity) => {
        let effects = entity.potionEffects
        effects.add('minecraft:regeneration', 10, 0, false, false)
    })
})
