StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:black_steel_ruby_ring')
        .texture('kubejs:item/black_steel_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.18, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.24, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heating_temperature", "heating_temperature", 5, "addition")
        .modifyAttribute("lhmiracleroad:healing", "healing", -0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_opal_ring')
        .texture('kubejs:item/black_steel_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.25, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.18, "multiply_total")
        .modifyAttribute("lhmiracleroad:hunger", "hunger", -0.2, "multiply_total")
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", -0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_amethyst_ring')
        .texture('kubejs:item/black_steel_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.21, "multiply_total")
        .modifyAttribute("lhmiracleroad:ranged_damage", "cooldown_reduction", 0.25, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_knockback", "generic.attack_knockback", -0.2, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -8, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_diamond_ring')
        .texture('kubejs:item/black_steel_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.2, "multiply_total")
        .modifyAttribute("lhmiracleroad:critical_hit_rate", "critical_hit_rate", 0.27, "multiply_total")
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", -4, "addition")
        .modifyAttribute("lhmiracleroad:injured", "injured", 0.25, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_pyrite_ring')
        .texture('kubejs:item/black_steel_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 9, "addition")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 7, "addition")
        .modifyAttribute("forge:block_reach", "block_reach", -0.25, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", -0.1, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_ender_ring')
        .texture('kubejs:item/black_steel_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 1, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", -3,"addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.25, "multiply_total")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", -6, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:black_steel_lapis_ring')
        .texture('kubejs:item/black_steel_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", -0.5, "addition")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 5.5, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", -0.2, "multiply_total")
        .modifyAttribute("lhmiracleroad:critical_hit_rate", "critical_hit_rate", -0.2, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_topaz_ring')
        .texture('kubejs:item/black_steel_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:burden", "burden", 30, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        .modifyAttribute("lhmiracleroad:hunger", "hunger", 0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", -100, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_sapphire_ring')
        .texture('kubejs:item/black_steel_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 300, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", -6,"addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.25, "multiply_total")
        .modifyAttribute("lhmiracleroad:injured", "injured", 0.15, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:black_steel_emerald_ring')
        .texture('kubejs:item/black_steel_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 15, "addition")
        .modifyAttribute("lhmiracleroad:healing", "healing", 0.5, "multiply_total")
        .modifyAttribute("lhmiracleroad:burden", "burden", -14, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", -0.2, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_cinnabar_ring')
        .texture('kubejs:item/black_steel_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:hunger", "hunger", 0.4, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 3, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", -3, "addition")
        .modifyAttribute("lhmiracleroad:healing", "healing", -0.15, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_jade_ring')
        .texture('kubejs:item/black_steel_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.2, "multiply_total")
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 5, "addition")
        .modifyAttribute("lhmiracleroad:critical_hit_damage", "critical_hit_damage", 0.4, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", -0.3, "multiply_total")
        )
        .tag("curios:ring")
})