StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:steel_ruby_ring')
        .texture('kubejs:item/steel_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.03, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.18, "multiply_total")
        .modifyAttribute("lhmiracleroad:healing", "healing", -0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_opal_ring')
        .texture('kubejs:item/steel_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.25, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", -0.15, "multiply_total")
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", -0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_amethyst_ring')
        .texture('kubejs:item/steel_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.21, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.12, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", -0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_diamond_ring')
        .texture('kubejs:item/steel_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:ranged_damage", "ranged_damage", 0.23, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -2, "addition")
        .modifyAttribute("lhmiracleroad:injured", "injured", 0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_pyrite_ring')
        .texture('kubejs:item/steel_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 7, "addition")
        .modifyAttribute("puffish_attributes:mining_speed", "armor_toughness", 0.18, "multiply_total")
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", -0.1, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_ender_ring')
        .texture('kubejs:item/steel_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 1.5, "addition")
        .modifyAttribute("lhmiracleroad:burden", "burden", 12, "addition")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -4, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:steel_lapis_ring')
        .texture('kubejs:item/steel_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 3.5, "addition")
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("puffish_attributes:stealth", "stealth", 0.5, "addition")
        .modifyAttribute("lhmiracleroad:burden", "burden", -12, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_topaz_ring')
        .texture('kubejs:item/steel_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:burden", "burden", 14, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.18, "multiply_total")
        .modifyAttribute("lhmiracleroad:hunger", "hunger", 0.09, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", -2.5, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_sapphire_ring')
        .texture('kubejs:item/steel_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 150, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.05, "multiply_total")
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", -0.15, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", -3, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:steel_emerald_ring')
        .texture('kubejs:item/steel_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 8, "addition")
        .modifyAttribute("lhmiracleroad:healing", "healing", 0.25, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -6, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", -0.15, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_cinnabar_ring')
        .texture('kubejs:item/steel_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 3.5,"addition")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 3.5, "addition")
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", -0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", -0.12, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_jade_ring')
        .texture('kubejs:item/steel_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.15, "multiply_total")
        .modifyAttribute("lhmiracleroad:critical_hit_damage", "critical_hit_damage", 0.25, "multiply_total")
        .modifyAttribute("lhmiracleroad:injured", "injured", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -6, "addition")
        )
        .tag("curios:ring")
})