StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:silver_ruby_ring')
        .texture('kubejs:item/silver_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 50, "addition")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.06, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 2, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_opal_ring')
        .texture('kubejs:item/silver_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.15, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_amethyst_ring')
        .texture('kubejs:item/silver_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 75, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 1, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_diamond_ring')
        .texture('kubejs:item/silver_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.18, "multiply_total")
        .modifyAttribute("lhmiracleroad:critical_hit_rate", "critical_hit_rate", 0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_pyrite_ring')
        .texture('kubejs:item/silver_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 4, "addition")
        .modifyAttribute("irons_spellbooks:pell_power", "spell_power", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 2, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_ender_ring')
        .texture('kubejs:item/silver_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 50, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:silver_lapis_ring')
        .texture('kubejs:item/silver_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.2, "multiply_total")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 1, "addition")
        .modifyAttribute("minecraft:generic.attack_knockback", "generic.attack_knockback", 0.3, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_topaz_ring')
        .texture('kubejs:item/silver_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:burden", "burden", 4, "addition")
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.15, "multiply_total")
        .modifyAttribute("lhmiracleroad:hunger", "hunger", 0.15, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_sapphire_ring')
        .texture('kubejs:item/silver_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 125, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 3, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:silver_emerald_ring')
        .texture('kubejs:item/silver_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 2, "addition")
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.2, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_cinnabar_ring')
        .texture('kubejs:item/silver_cinabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 2.5, "addition")
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 50, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_jade_ring')
        .texture('kubejs:item/silver_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 3, "addition")
        .modifyAttribute("lhmiracleroad:critical_hit_damage", "critical_hit_damage", 0.25, "multiply_total")
        )
        .tag("curios:ring")
})