StartupEvents.registry('item', event => {
        //戒指指环蓝板
        event.create('shiny_ornaments:copper_ring_base')
        .texture('kubejs:item/copper_ring_base')
        event.create('shiny_ornaments:silver_ring_base')
        .texture('kubejs:item/silver_ring_base')
        event.create('shiny_ornaments:sterling_silver_ring_base')
        .texture('kubejs:item/sterling_silver_ring_base')
        event.create('shiny_ornaments:gold_ring_base')
        .texture('kubejs:item/gold_ring_base')
        event.create('shiny_ornaments:rose_gold_ring_base')
        .texture('kubejs:item/rose_gold_ring_base')
        event.create('shiny_ornaments:steel_ring_base')
        .texture('kubejs:item/steel_ring_base')
        event.create('shiny_ornaments:black_steel_ring_base')
        .texture('kubejs:item/black_steel_ring_base')
        //普通戒指
        event.create('shiny_ornaments:copper_ring')
        .texture('kubejs:item/copper_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 2, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:sterling_silver_ring')
        .texture('kubejs:item/sterling_silver_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.09, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:silver_ring')
        .texture('kubejs:item/silver_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", 0.1, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:gold_ring')
        .texture('kubejs:item/gold_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.04, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:rose_gold_ring')
        .texture('kubejs:item/rose_gold_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:healing", "healing", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:steel_ring')
        .texture('kubejs:item/steel_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:black_steel_ring')
        .texture('kubejs:item/black_steel_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:critical_hit_damage", "critical_hit_damage", 0.09, "multiply_total")
        )
        .tag("curios:ring")
        .texture('kubejs:item/black_steel_ring_base')
        
        //精锻戒指
        event.create('shiny_ornaments:rose_gold_delicacy_ring')
        .texture('kubejs:item/rose_gold_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:healing", "healing", 0.1, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 2.5, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:steel_delicacy_ring')
        .texture('kubejs:item/steel_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.1, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:black_steel_delicacy_ring')
        .texture('kubejs:item/black_steel_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("puffish_attributes:life_steal", "life_steal", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -3, "addition")
        )
        .tag("curios:ring")
})