StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:golden_ruby_ring')
        .texture('kubejs:item/golden_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.09, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.1, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 2, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_opal_ring')
        .texture('kubejs:item/golden_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.16, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.12, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_amethyst_ring')
        .texture('kubejs:item/golden_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.15, "multiply_total")
        .modifyAttribute("lhmiracleroad:ranged_damage", "ranged_damage", 0.12, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_diamond_ring')
        .texture('kubejs:item/golden_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.1, "multiply_total")
        .modifyAttribute("lhmiracleroad:critical_hit_rate", "critical_hit_rate", 0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_pyrite_ring')
        .texture('kubejs:item/golden_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("puffish_attributes:mining_speed", "mining_speed", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 4, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_ender_ring')
        .texture('kubejs:item/golden_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("lhmiracleroad:burden", "burden", 8, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:golden_lapis_ring')
        .texture('kubejs:item/golden_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("puffish_attributes:stealth", "stealth", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 1.5, "addition")
        .modifyAttribute("minecraft:generic.attack_knockback", "generic.attack_knockback", 0.3, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_topaz_ring')
        .texture('kubejs:item/golden_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:burden", "burden", 16, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.05, "multiply_total")
        .modifyAttribute("lhmiracleroad:hunger", "hunger", 0.15, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_sapphire_ring')
        .texture('kubejs:item/golden_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 80, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.18, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 3, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:golden_emerald_ring')
        .texture('kubejs:item/golden_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 8, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 3, "addition")
        .modifyAttribute("lhmiracleroad:healing", "healing", 0.15, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_cinnabar_ring')
        .texture('kubejs:item/golden_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 6, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 2.5, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 2, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_jade_ring')
        .texture('kubejs:item/golden_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.12, "multiply_total")
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 2, "addition")
        .modifyAttribute("lhmiracleroad:critical_hit_damage", "critical_hit_damage", 0.18, "multiply_total")
        )
        .tag("curios:ring")

})