StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:copper_ruby_ring')
        .texture('kubejs:item/copper_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.09, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.12, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 0.2, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:copper_opal_ring')
        .texture('kubejs:item/copper_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.12, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:copper_amethyst_ring')
        .texture('kubejs:item/copper_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.15, "multiply_total")
        .modifyAttribute("lhmiracleroad:ranged_damage", "cooldown_reduction", 0.2, "multiply_total")
        .modifyAttribute("lhmiracleroad:soul_increase", "soul_increase", 0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:copper_diamond_ring')
        .texture('kubejs:item/copper_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.18, "multiply_total")
        .modifyAttribute("lhmiracleroad:critical_hit_rate", "critical_hit_rate", 0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:copper_pyrite_ring')
        .texture('kubejs:item/copper_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 4, "addition")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 4, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_ender_ring')
        .texture('kubejs:item/copper_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 1, "addition")
        .modifyAttribute("lhmiracleroad:burden", "burden", 12, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.15, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:copper_lapis_ring')
        .texture('kubejs:item/copper_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 2, "addition")
        .modifyAttribute("minecraft:generic.attack_knockback", "generic.attack_knockback", 0.3, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_topaz_ring')
        .texture('kubejs:item/copper_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("lhmiracleroad:burden", "burden", 10, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        .modifyAttribute("lhmiracleroad:hunger", "hunger", 0.3, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_sapphire_ring')
        .texture('kubejs:item/copper_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 80, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.3, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 0.2, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:copper_emerald_ring')
        .texture('kubejs:item/copper_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 6, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 15, "multiply_total")
        .modifyAttribute("lhmiracleroad:healing", "healing", 0.25, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_cinnabar_ring')
        .texture('kubejs:item/copper_cinabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 4, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 0.15,"multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 0.3, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_jade_ring')
        .texture('kubejs:item/copper_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 3, "addition")
        .modifyAttribute("lhmiracleroad:critical_hit_damage", "critical_hit_damage", 0.25, "multiply_total")
        )
        .tag("curios:ring")
})